** What is  /providers/ definition?
   It's a property of AppModule or AppComponent and it's used for creating /dependencies/.
   Those /dependencies/ then will be injected and used in classes without creating a new instance.
** What is /dependency/ ?
   /Dependency/ is an instance of class, this instance then will be injected into classes, and 
   be used there.
** What is /declare/, /export/, /import/, /provide/ and /boostrap/ in ngModule?
*** _Declare_ : list component, directive and pipi belong to ngModule
*** _Export_: list classes which will be used in template
*** _Import_: to import an ngModule, then used its component, directive, pipe 
*** _Provide_: List services that component can used instead of creating a new instance
*** _Boostrap_: List the root app module to start up
** Angular does not do live reloading ?
   reference: https://github.com/angular/angular-cli/issues/1610
   - remove node_modules and reinstall node packages.
   - run server with poll flag: ng server --poll=1000
** How to an event in child component can affect parent component ?
   - The child component has an event emiter instance
   - The parent component has an even handler function
   
   for example: 
   #+BEGIN_SRC typescript
   <child-component (createItemEmitter)='handleCreateItem($event)'> </child-component>
   #+END_SRC
   the parent component has a function name handleCreateItem($event). The child component has a createItemEmitter, 
   when user click a button in the child component. It emits an events. On the parent component, there is an event 
   handler that has been match to handle it.
   
   it's required to output event emitter in the child component.
   #+BEGIN_SRC language
   @Output() createItemEmitter = new EventEmitter<any>();
   #+END_SRC
   On the parent component, event handler looks alike:
   #+BEGIN_SRC typescript
   createItemHandler(any): void { // create a new item and push to an array maybe.}
   #+END_SRC
   EventEmitter is generic type class, which mean that I can decide how emit data structure could be, the data structure 
   that passs into event handler must has the same data structure as event emitter.For example:
   #+BEGIN_SRC language
   @Output() createItemEmitter = new EventEmitter<{name: string}>(); // child component
   handleCreateItem({name: string}) {} // parent component
   #+END_SRC
** What is local reference ?
   In template, document object model can interact with other via it's #name. for example:
   #+BEGIN_SRC html
   <input #nameInput> </input>
   <button (click)='onClick(nameInput)'> </button>
   #+END_SRC
   By this way, a dom has been tagged and pass into another dom's function to process. 
   It happens on the template only so, it's called local reference
** How to get access to template & Document Object Model ?
   Beside local reference, that give access only on template. It's another way to 
   access _data object model_ from component class is using decorator @ViewChild.
   #+BEGIN_SRC html
   <input #nameInput> </input>
   #+END_SRC
   #+BEGIN_SRC typescript
   @ViewChild('nameInput') nameInput;
   #+END_SRC
** Life cycle of a component?
   - ngOnChanges
   - ngOnInit
   - ngDoCheck
   - ngAfterContentInit
   - ngAfterContentChecked
   - ngAfterViewInit
   - ngAfterViewChecked
   - ngOnDestroy

       
