** How to get sha256 sum of file
#+BEGIN_SRC shell
sha256sum path_to_file
#+END_SRC
** How to add new user
#+BEGIN_SRC shell
useradd kmt
passwd kmt
#+END_SRC
** How to extract tar.gz
#+BEGIN_SRC shell
tar -vxzf abc.tar.gz
#+END_SRC
** How to reload the bashrc, zshrc file
#+BEGIN_SRC shell
source .bashrc
source .zshrc
#+END_SRC
** How to open a port with firewall-cmd
#+BEGIN_SRC shell
firewall-cmd --permanent add-port=8888/tcp
firewall-cmd --reload
#+END_SRC
** How to open internet for centos
#+BEGIN_SRC shell
dhclient -v
#+END_SRC
** Block website with host file
- Edit hosts at /etc/hosts
- Add localhost xxx.com to block xxx.com site
** How to use apt to find all version of package
#+BEGIN_SRC shell
apt-cache policy elixir
#+END_SRC
** How to change password
*** Current user `passwd`
*** Another user `passwd user_name`

** How to list all version of package (yum)
#+BEGIN_SRC shell
yum --showduplicates list httpd
#+END_SRC
** How to install package with specify version(yum)
yum install httpd-version
** How to know which package we need to install given command/description
#+BEGIN_SRC shell
yum whatprovides autoconf automake xxxx
#+END_SRC
** How to ignore kernel when do upgrade system with dnf (dnf upgrade)
   Edit file /etc/dnf/dnf.conf
   #+BEGIN_SRC conf
   exclude=kernel*
   #+END_SRC
** How to swap version of java
- Download favor java from Oracle website
#+BEGIN_SRC shell
sudo alternatives --config java
#+END_SRC
- Choose prefer java version.
** Where is the config file of ssh
   /etc/ssh/ssh_config
** What is the role of known_hosts and authorized_keys
   known_hosts -> when client connect to server, public key of _SERVER_ will be stored at _CLIENT's known_hosts_
   authorized_keys -> when server accept client's public keys, _SERVER_ will store _CLIENT's public key_ in authorized_keys
** How to restart ssh
   #+BEGIN_SRC shell
   service sshd restart
   #+END_SRC

** What is >> and >
   >>: refers to append the output to end of file
   >: refers to overwrite the
** What is UEFI(Unified Extensible Firmware Interface), EFI(Extensible Firmware Interface), Booloader

** How to mout a usb in terminal
** How to unmount a usb in terminal
** How to write a file.iso to a usb
    #+BEGIN_SRC bash
   dd bs=4M if=/path/to/archlinux.iso of=/dev/sdx status=progress && sync
   #+END_SRC
** How to list all disk
   #+BEGIN_SRC bash
   fdisk -l
   #+END_SRC

** How to add an user to a group
   usermod -a -G _group_name_ _username_
** How to list all network interface
   #+BEGIN_SRC bash
   ip link
   #+END_SRC

** How to start/end  up/down a network interface
   #+BEGIN_SRC bash
   ip link set interface up/down
   #+END_SRC
** How to mount a partition when an OS boot
   Edit file: /etc/fstab and append
   #+BEGIN_SRC text
   /dev/sdaX /mount_point sdaX_partition_format
   #+END_SRC
** How to setup host so that allow clients accessing via ssh connection.
*** Create the RSA Key Pair on client machine
#+BEGIN_SRC shell
ssh-keygen -t rsa
#+END_SRC
*** Add public key to the .ssh/authorized_keys on the host

** How to open a port for service at any port professionally
*** Create firewall service configuration: my-service.xml in /etc/firewalld/services/
#+BEGIN_SRC xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>My Service</short>
  <description>This option allows My service to use tcp port 80</description>
  <port protocol="tcp" port="80"/>
</service>
#+END_SRC
*** Add a new service to firewall-cmd: firewall-cmd --permanent --add-service=my-service
*** Reload firewall-cmd: firewall-cmd --reload
*** Check firewall service list: firewall-cmd --list-services

** How to run application with port 80 (any port under 2000)
#+BEGIN_SRC sh
sudo setcap CAP_NET_BIND_SERVICE=+eip path_to_binary_file
#+END_SRC
** How to set chmod for ssh keys
|-----------------+-------+-------+-------+-------+--------+--------|
| file name       | chmod | user  | group | other | server | client |
|-----------------+-------+-------+-------+-------+--------+--------|
| ~/.ssh          |   700 | u+wrx |       |       | x      | x      |
| id_rsa          |   600 | u+wr  |       |       |        | x      |
| id_rsa.pub      |   644 | u+wr  | g+r   | o+r   |        | x      |
| authorized_keys |   644 | u+wr  | g+r   | o+r   | x      |        |
| known_hosts     |   644 | u+wr  | g+r   | g+r   |        | x      |
|-----------------+-------+-------+-------+-------+--------+--------|
** How to subscribe RHEL system?
#+BEGIN_SRC sh
subscription-manager register;
subscription-manager refresh;
subscription-manager attach;
#+END_SRC
** How to get current zone with firewall-cmd?
* KEYSCAN ISSUE gather all public key or not ??????
