
** How to get sha256 sum of file
#+BEGIN_SRC shell
sha256sum path_to_file
#+END_SRC
** How to add new user
#+BEGIN_SRC shell
useradd kmt
passwd kmt
#+END_SRC
** How to extract tar.gz
#+BEGIN_SRC shell
tar -vxzf abc.tar.gz
#+END_SRC
** How to reload the bashrc, zshrc file
#+BEGIN_SRC shell
source .bashrc
source .zshrc
#+END_SRC
** How to open a port with firewall-cmd
#+BEGIN_SRC shell
firewall-cmd --permanent add-port=8888/tcp
firewall-cmd --reload
#+END_SRC
** How to open internet for centos
#+BEGIN_SRC shell
dhclient -v
#+END_SRC
** Block website with host file
- Edit hosts at /etc/hosts
- Add localhost xxx.com to block xxx.com site
** How to use apt to find all version of package
#+BEGIN_SRC shell
apt-cache policy elixir
#+END_SRC
** How to change password
*** Current user `passwd`
*** Another user `passwd user_name`

** How to list all version of package (yum)
#+BEGIN_SRC shell
yum --showduplicates list httpd
#+END_SRC
** How to install package with specify version(yum)
yum install httpd-version
** How to know which package we need to install given command/description
#+BEGIN_SRC shell
yum whatprovides autoconf automake xxxx
#+END_SRC
** How to ignore kernel when do upgrade system with dnf (dnf upgrade)
   Edit file /etc/dnf/dnf.conf
   #+BEGIN_SRC conf
   exclude=kernel*
   #+END_SRC
** How to swap version of java
- Download favor java from Oracle website
#+BEGIN_SRC shell
sudo alternatives --config java
#+END_SRC
- Choose prefer java version.
** Where is the config file of ssh
   /etc/ssh/ssh_config
** What is the role of known_hosts and authorized_keys
   known_hosts -> when client connect to server, public key of _SERVER_ will be stored at _CLIENT's known_hosts_
   authorized_keys -> when server accept client's public keys, _SERVER_ will store _CLIENT's public key_ in authorized_keys
** How to restart ssh
   #+BEGIN_SRC shell
   service sshd restart
   #+END_SRC

** What is >> and >
   >>: refers to append the output to end of file
   >: refers to overwrite the
** What is UEFI(Unified Extensible Firmware Interface), EFI(Extensible Firmware Interface), Booloader

** How to mout a usb in terminal
** How to unmount a usb in terminal
** How to write a file.iso to a usb
    #+BEGIN_SRC bash
   dd bs=4M if=/path/to/archlinux.iso of=/dev/sdx status=progress && sync
   #+END_SRC
** How to list all disk
   #+BEGIN_SRC bash
   fdisk -l
   #+END_SRC

** How to add an user to a group
   usermod -a -G _group_name_ _username_
** How to list all network interface
   #+BEGIN_SRC bash
   ip link
   #+END_SRC

** How to start/end  up/down a network interface
   #+BEGIN_SRC bash
   ip link set interface up/down
   #+END_SRC
** How to mount a partition when an OS boot
   Edit file: /etc/fstab and append
   #+BEGIN_SRC text
   /dev/sdaX /mount_point sdaX_partition_format
   #+END_SRC
** How to setup host so that allow clients accessing via ssh connection.
*** Create the RSA Key Pair on client machine
#+BEGIN_SRC shell
ssh-keygen -t rsa
#+END_SRC
*** Add public key to the .ssh/authorized_keys on the host

** How to open a port for service at any port professionally
*** Create firewall service configuration: my-service.xml in /etc/firewalld/services/
#+BEGIN_SRC xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>My Service</short>
  <description>This option allows My service to use tcp port 80</description>
  <port protocol="tcp" port="80"/>
</service>
#+END_SRC
*** Add a new service to firewall-cmd: firewall-cmd --permanent --add-service=my-service
*** Reload firewall-cmd: firewall-cmd --reload
*** Check firewall service list: firewall-cmd --list-services

** How to run application with port 80 (any port under 2000)
#+BEGIN_SRC sh
sudo setcap CAP_NET_BIND_SERVICE=+eip path_to_binary_file
#+END_SRC
** How to set chmod for ssh keys
|-----------------+-------+-------+-------+-------+--------+--------|
| file name       | chmod | user  | group | other | server | client |
|-----------------+-------+-------+-------+-------+--------+--------|
| ~/.ssh          |   700 | u+wrx |       |       | x      | x      |
| id_rsa          |   600 | u+wr  |       |       |        | x      |
| id_rsa.pub      |   644 | u+wr  | g+r   | o+r   |        | x      |
| authorized_keys |   644 | u+wr  | g+r   | o+r   | x      |        |
| known_hosts     |   644 | u+wr  | g+r   | g+r   |        | x      |
|-----------------+-------+-------+-------+-------+--------+--------|
** How to subscribe RHEL system?
#+BEGIN_SRC sh
  subscription-manager register;
  subscription-manager refresh;
  subscription-manager attach;

** How to mount a network drive using NFS protocol?
#+BEGIN_SRC sh
  mkdir /mnt/NAS/disk_1;
  mount --types nfs 192.168.x.x:/directory_X /mnt/NAS/disk_1;
#+END_SRC

** How to mount a network drive (nfs protocol) at start-up?
   Edit file /etc/fstab, append an entry
#+BEGIN_SRC text
192.168.x.x:/directory_X /mnt/NAS/disk_1 nfs defaults 0 0
#+END_SRC

** How to mount a network drive using CIFS protocol?
#+BEGIN_SRC sh
  mkdir /mnt/NAS/disk_1;
  mount --types cifs -o uid=1000,gid=1000,vers=3,credentials=/home/yourhome/.nasauth //192.168.x.x/directory_X /mnt/NAS/disk_1;
#+END_SRC

It's important to append `uid` and `gid`, these attributes will be used to assign ownership of mounted directory. After mounting, check ownership with following command `ls -lah`.

To extract `uid` and `gid` numbers, use the following command.

#+BEGIN_SRC sh
  $ id -u
  $ id -g
#+END_SRC

- `id`: get all attribute of current login user
- `id -u`: get `uid` of current login user
- `id -g`: get `gid` of current login user

In addition, to hide authentication info from fstab file. Credentials data is passed by attribute named `credentials` with `600` permission. This is credential schema.

#+BEGIN_SRC text
username=xxx
password=yyy
#+END_SRC

** How to mount a network drive (CIFS protocol) at start-up?
#+BEGIN_SRC text
//192.168.x.x/directory_X /mnt/NAS/disk_1 cifs uid=1000,gid=1000,vers=3,credentials=/home/yourhome/.auth 0 0
#+END_SRC

** How to list all `mount service` with systemctl
#+BEGIN_SRC sh
systemctl list-units --type=mount
#+END_SRC

** How to update systemd after unit updates?
#+BEGIN_SRC sh
systemctl daemon-reload
#+END_SRC

** How to fix auto-mount issue due to network connection?
In this directory ~/etc/NetworkManager/dispatcher.d~, create a file named ~mount-nas-volumes.sh~ with the
following content.
#+BEGIN_SRC bash
#!/bin/bash

INTERFACE="$1"
STATUS="$2"

if [ "$STATUS" = "up" ]; then
    mount -a
fi
#+END_SRC

After that, set the file executable
#+BEGIN_SRC bash
chmod +x mount-nas-volumes.sh
#+END_SRC

** How to add L2TP module to network manager to support VPN L2TP?
#+BEGIN_SRC sh
sudo dnf install xl2tpd
sudo dnf install NetworkManager-l2tp
sudo dnf install NetworkManager-l2tp-gnome
sudo service NetworkManager restart
#+END_SRC

** How to denote a base of number?
- 0b11101: (`b`) Binary - base 2
- 0o35   : (`o`) Octal, denoted by an o, base 8
- 0d29   : (`d`) Decimal, this is unusual because we assume numbers without a prefix are decimal, base 10
- 0x1D   : (`x`) Hexadecimal, base 16

** Where is nautilus script?
#+BEGIN_SRC sh
~/.local/share/nautilus/scripts
#+END_SRC

** How to debug nautilus script?
Open terminal and type
#+BEGIN_SRC sh
nautilus --browser
#+END_SRC

** Where is systemctl service file config?
- **/usr/lib/systemd/user**: it's for systemctl --user services
- **/etc/systemd/system**: it's for systemctl os-wide services

** How to get current zone with firewall-cmd?

** How to get date/time from cmd?
~-u~ is for UTC, ignore this flag to get curernt datetime in local timezone
#+BEGIN_SRC sh
$ date +'%Y-%m-%d %H:%M:%S.%N' -u
2022-12-16 02:00:28.311535408

$ date +'%Y-%m-%d %H:%M:%S' -u
2022-12-16 02:01:31
#+END_SRC

** How to know if OS using XORG or Wayland as display server?
#+BEGIN_SRC sh
echo $XDG_SESSION_TYPE
#+END_SRC

** How to make gif from image?

#+BEGIN_SRC bash
sudo dnf install ImageMagick
convert -resize 640x480 -delay 0 -loop 0 ./0001/*.png 0001.gif
#+END_SRC

** How to remove journalctl log?
- To check the size of journalctl log.
#+BEGIN_SRC shell
$ du -hs /var/log/journal  # option 1
$ journalctl --disk-usage  # option 2
#+END_SRC

- To remove log
#+BEGIN_SRC shell
$ journalctl --vaccum-size 100M # -- Reduce disk usage below specified size (100MB)
$ journalctl --vaccum-time 7d    # -- Remove journal files older than specified time (7 days)
#+END_SRC

** How to add dns for fedora in terminal?
- Step 1: get a list of network interface and its dns status
#+BEGIN_SRC shell
$ resolvectl status

Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: foreign

Link 2 (eth0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (eth1)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (docker0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
#+END_SRC

- Step 2: Add dns to network interface

#+BEGIN_SRC shell
$ resolvectl dns eth0 1.1.1.1 8.8.8.8 8.8.4.4
$ resolvectl dns eth1 1.1.1.1 8.8.8.8 8.8.4.4
$ resolvectl status

Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: foreign

Link 2 (eth0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1 8.8.8.8 8.8.4.4

Link 3 (eth1)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1 8.8.8.8 8.8.4.4

Link 4 (docker0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
#+END_SRC

** How to fix boot error with nvme?
Reason: The Autonomous Power State Transitions(APST) was causing the freezes.

Step 1: Go to rescue mode and choose boot entry that work
Step 2: Edit ~/etc/default/grub~, append ~nvme_core.default_ps_max_latency_us=0~ to ~GRUB_CMDLINE_LINUX="..."~
Step 3: Update grub, then reboot
#+BEGIN_SRC sh
# For Fedora, Arch Linux, etc.
sudo grub2-mkconfig -o /boot/grub2/grub.cfg

# For Ubuntu, Debian, Linux Mint, etc. (debian-based)
sudo update-grub
#+END_SRC

references:
- Random Freezes in Kubuntu 20.04, https://askubuntu.com/a/1274020
- Fixing NVME SSD Problems On Linux, https://tekbyte.net/fixing-nvme-ssd-problems-on-linux/

** How to assign particular private key for ssh?
#+BEGIN_SRC language

Host myshortname realname.example.com
    HostName realname.example.com
    IdentityFile ~/.ssh/realname_rsa # private key for realname
    User remoteusername

Host myother realname2.example.org
    HostName realname2.example.org
    IdentityFile ~/.ssh/realname2_rsa  # different private key for realname2
    User remoteusername
#+END_SRC

** A shell one-liner for an infinite loop in (sh/zsh/bash compatible)
#+BEGIN_SRC sh
while true; do date; sleep 5; done
#+END_SRC

** How to show key which is typed?
#+BEGIN_SRC sh
$ showkey -a
#+END_SRC

** How to refresh gnome ~app.desktop~?
#+BEGIN_SRC sh
update-desktop-database ~/.local/share/applications
#+END_SRC

** How to add static route with `nmcli` with tunnel interface (globalprotect vpn)?
After we got access via vpn, we grant new IP, in this case, it's `172.16.20.123`
Because, it's a tunnel, we use 172.16.20.123 as gateway.
#+BEGIN_SRC sh
  $ nmcli connection edit gpd0
  # go to nmcli interactive config editor.
  set ipv4.routes 172.17.xxx.xxx/32 172.16.20.123
  set ipv4.routes 172.19.xxx.xxx/32 172.16.20.123
  set ipv4.gateway 172.16.20.123
  save persistent
  quit
#+END_SRC

* KEYSCAN ISSUE gather all public key or not ??????
