** Create user
  #+BEGIN_SRC sql
  CREATE USER username;
  #+END_SRC
** Create user with ability to createdb;
  #+BEGIN_SRC sql
  CREATE USER username createdb;
  #+END_SRC
** Change password of user
#+BEGIN_SRC sql
alter user ABC encrypted password 'ABC_password'
#+END_SRC*
** Alter the role of user;
  #+BEGIN_SRC sql
  ALTER USER username createdb;
  #+END_SRC
** How to make new database
   #+BEGIN_SRC sql
   create database database_name with owner = owner_name;
   #+END_SRC
** How to drop database
   #+BEGIN_SRC sql
   drop database database_name
   #+END_SRC
** Export the data from the database
- File sql mode
  #+BEGIN_SRC shell
    pg_dump -O -x db_name > output.sql
    pg_dump -h 127.0.0.1 -p 15432 -d iea_dev -x db_name > file_export.sql
  #+END_SRC

- Dir mode
  #+BEGIN_SRC sh
    /usr/bin/pg_dump --verbose --host=127.0.0.1 --port=9155 --username=linh --format=d --file /home/nguyenvinhlinh/Temporary/database-backup/dump-202305110112 -n public db_name_here
  #+END_SRC
** Import the data to the databaes
- File sql mode
  #+BEGIN_SRC shell
  psql db_name < output.sql
  #+END_SRC
- Dir mode
  #+BEGIN_SRC sh
  /usr/bin/pg_restore --verbose --host=127.0.0.1 --port=9155 --username=linh --format=d --dbname=DB_NAME_HERE /home/nguyenvinhlinh/Temporary/database-backup/dump-bahamas-etl-production-202305110112
  #+END_SRC
** View currrent database in psql
  #+BEGIN_SRC sql
  select * from current_database();
  #+END_SRC
** View a list of database
  #+BEGIN_SRC sql
  \l
  #+END_SRC
** Connect/select to particular database
  #+BEGIN_SRC sql
  \c database_name
  #+END_SRC

** How to dump all data of postgres
   #+BEGIN_SRC shell
   su postgres
   pg_dumpall -f dump.sql
   #+END_SRC
** How to restore data from pg_dumpall
#+BEGIN_SRC shell
su postgres
psql < dumpsql.sql
#+END_SRC

** Different between _varchar_ and _char_ data type
   The output of data when fetching is different.
   - varchar(5): it uses 5 slot to store character. if value's length is 2 for example: "Hi",
     it will return "Hi"
   - char(5): it uses 5 slot to store character. if value's length is 2 for example: "Hi",
     it will return "Hi   ". Note that those 3 space characters after "i" letter.

** Where is the default installation of postgres?
   /usr/pgsql-X -> X is the major verion
** Where is the default data directory?
   /var/lib/pgsql
** How to find records when `where` working with array-type column
   #+BEGIN_SRC sql
   select * from temp.table_name where array_type_column_name @> '{term}';
   #+END_SRC

** How to set next id sequence value to max(id) from table?
#+BEGIN_SRC sql
SELECT setval('table_id_seq', (SELECT MAX(id) FROM table));
#+END_SRC

** How to check vacum status?
#+BEGIN_SRC sql
SELECT heap_blks_scanned/cast(heap_blks_total as numeric)*100 as heap_blks_percent, progress.*, activity.query
FROM pg_stat_progress_vacuum AS progress
INNER JOIN pg_stat_activity AS activity ON activity.pid = progress.pid;
#+END_SRC

Reference: https://dba.stackexchange.com/a/245163

** How to vacuum table and reclaim space for OS?
#+BEGIN_SRC sql
VACUUM (FULL, VERBOSE) public."TABLE_NAME";
#+END_SRC


pg_dump --file schema_odm_cusdec_20190603_183100.sql --data-only --host 127.0.0.1 --port 5432 --username nguyenvinhlinh --verbose --format=p --schema "odm_cusdec" "risk_management_system_dev
psql -h 127.0.0.1 -p 5432 -d risk_management_system_dev -U nguyenvinhlinh < ~/Dropbox/Projects/MexicoRMS-Demo/SQL/public/schema_public_20190529-023200.sql

** How to commend on table's columns?
#+BEGIN_SRC sql
COMMENT ON COLUMN public.TABLE_NAME_HERE."type" IS 'YOUR_COMMENT_HERE';
#+END_SRC

** How to install postgresql client and setup dbeaver for dump/restore ?
- Step 1: install ~postgresql~ client.
#+BEGIN_SRC sh
$ sudo dnf install postgresql -y
#+END_SRC
- Step 2: In terminal, find parent directory which contain ~pgsql~
#+BEGIN_SRC sh
$ which pgsql
/usr/bin/pg_dump
#+END_SRC
- Step 2: In DBeaver, local client, add home, set home path to ~/usr/bin~
